name: dart_pet_project
description: A sample command-line application with basic argument parsing.
version: 0.0.1
# repository: https://github.com/my_org/my_repo

environment:
  sdk: ^3.5.3

# Add regular dependencies here.
dependencies:
  args: ^2.4.2
  drift: ^2.20.2
  http: ^1.2.2
  sqlite3: ^2.4.6
  shelf: ^1.1.0
  shelf_router: ^1.1.2
  shelf_static: ^1.1.0
  dotenv: ^4.2.0
  dio: ^5.7.0

  freezed_annotation: ^2.4.4
  json_annotation: ^4.9.0

dev_dependencies:
  lints: ^4.0.0
  test: ^1.24.0
  drift_dev: ^2.20.3
  freezed: ^2.5.7
  build_runner: ^2.4.12
  json_serializable: ^6.8.0
